name: Limit Open PRs

on: pull_request

jobs:
  limit-prs:
    runs-on: ubuntu-latest
    steps:
    - name: Check number of open PRs and convert to draft if necessary
      run: |
        # Get the number of open PRs
        PR_COUNT=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls?state=open" | jq length)
        echo "Open PRs: $PR_COUNT"
        
        # Check if the limit is reached or exceeded
        if [[ "$PR_COUNT" -ge 5 ]]; then
          echo "Limit of 5 open PRs reached. Converting this PR to draft."

          # Convert the current PR to draft
          curl -X PATCH -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" \
            -d '{"draft": true}'
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
